package us.byteb.advent.year2025;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.*;

class Day07Test {

  private static final String INPUT =
      """
      .......S.......
      ...............
      .......^.......
      ...............
      ......^.^......
      ...............
      .....^.^.^.....
      ...............
      ....^.^...^....
      ...............
      ...^.^...^.^...
      ...............
      ..^...^.....^..
      ...............
      .^.^.^.^.^...^.
      ...............
      """;

  @Test
  void testPart1() {
    assertEquals(21L, Day07.countSplits(INPUT));
  }

  @Test
  void testPart2() {
    assertEquals(40L, Day07.countTimelines(INPUT));
  }
}
